# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_username_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmethod',
            name='provider_id',
            field=models.CharField(
                choices=[],
                max_length=50, unique=True),
        ),
    ]
