# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 08:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helusers', '0001_add_ad_groups'),
        ('users', '0008_provider_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='include_ad_groups',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='ad_groups',
            field=models.ManyToManyField(blank=True, to='helusers.ADGroup'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loginmethod',
            name='provider_id',
            field=models.CharField(choices=[('espoo_adfs', 'Espoo ADFS'), ('facebook', 'Facebook'), ('github', 'GitHub'), ('google', 'Google'), ('helsinki_adfs', 'Helsinki ADFS'), ('yletunnus', 'YleTunnus')], max_length=50, unique=True),
        ),
    ]
