# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_create_model_oidc_client_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oidcclientoptions',
            options={'verbose_name': 'OIDC Client Options', 'verbose_name_plural': 'OIDC Client Options'},
        ),
        migrations.AlterField(
            model_name='loginmethod',
            name='provider_id',
            field=models.CharField(choices=[('espoo_adfs', 'espoo_adfs'), ('facebook', 'facebook'), ('github', 'github'), ('google', 'google'), ('helsinki_adfs', 'helsinki_adfs')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='oidcclientoptions',
            name='oidc_client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='oidc_provider.Client', verbose_name='OIDC Client'),
        ),
    ]
