# Generated by Django 2.0.6 on 2018-06-29 13:53

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('users', '0012_social_auth_providers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='timestamp')),
                ('ip_address', models.CharField(max_length=50, null=True, blank=True, verbose_name='IP address')),
                ('geo_location', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='geo location')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_login_entries', to='services.Service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'user login entry',
                'verbose_name_plural': 'user login entries',
                'ordering': ('timestamp',),
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='loginmethod',
            name='provider_id',
            field=models.CharField(choices=[('espoo_adfs', 'espoo_adfs'), ('facebook', 'facebook'), ('github', 'github'), ('google', 'google'), ('helsinki_adfs', 'helsinki_adfs'), ('yletunnus', 'yletunnus')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='userloginentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_entries', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
