# Generated by Django 2.0.13 on 2019-04-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_add_user_login_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmethod',
            name='provider_id',
            field=models.CharField(choices=[('eduhelfi', 'eduhelfi'), ('espoo', 'espoo'), ('facebook', 'facebook'), ('github', 'github'), ('google', 'google'), ('helsinki_adfs', 'helsinki_adfs'), ('helsinki_library_asko_adfs', 'helsinki_library_asko_adfs'), ('suomifi', 'suomifi'), ('yletunnus', 'yletunnus')], max_length=50, unique=True),
        ),
    ]
