# Generated by Django 2.1.8 on 2019-06-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_application__post_logout_redirect_uris'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginmethod',
            name='background_color',
        ),
    ]
