# Generated by Django 2.1.8 on 2019-06-14 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_loginmethod_background_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='_post_logout_redirect_uris',
            new_name='post_logout_redirect_uris',
        ),
    ]
