# Generated by Django 2.1.11 on 2019-09-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_post_logout_redirect_uris'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedOrigin',
            fields=[
                ('key', models.CharField(max_length=300, primary_key=True, serialize=False)),
            ],
        ),
    ]
