# Generated by Django 2.1.15 on 2020-11-02 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_populate_cors_allowed_origins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmethod',
            name='provider_id',
            field=models.CharField(choices=[('eduhelfi', 'eduhelfi'), ('espoo', 'espoo'), ('facebook', 'facebook'), ('github', 'github'), ('google', 'google'), ('helsinki_adfs', 'helsinki_adfs'), ('helsinki_library_asko_adfs', 'helsinki_library_asko_adfs'), ('helusername', 'helusername'), ('suomifi', 'suomifi'), ('yletunnus', 'yletunnus')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='oidcclientoptions',
            name='oidc_client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='oidc_provider.Client', verbose_name='OIDC Client'),
        ),
    ]
