# Generated by Django 2.2.18 on 2021-05-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_change_choicefield_and_related_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmethod',
            name='provider_id',
            field=models.CharField(choices=[('eduhelfi', 'eduhelfi'), ('espoo', 'espoo'), ('facebook', 'facebook'), ('github', 'github'), ('google', 'google'), ('helsinki_adfs', 'helsinki_adfs'), ('helsinki_library_asko_adfs', 'helsinki_library_asko_adfs'), ('heltunnistussuomifi', 'heltunnistussuomifi'), ('helusername', 'helusername'), ('suomifi', 'suomifi'), ('tunnistamo', 'tunnistamo'), ('yletunnus', 'yletunnus')], max_length=50, unique=True),
        ),
    ]
