# Generated by Django 2.2.18 on 2021-05-03 09:30

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0022_update_loginmethod_provider_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='TunnistamoSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Session data')),
                ('created_at', models.DateTimeField(verbose_name='Created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tunnistamo_sessions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Tunnistamo Session',
                'verbose_name_plural': 'Tunnistamo Sessions',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='SessionElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(verbose_name='Created at')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='users.TunnistamoSession', verbose_name='Tunnistamo Session')),
            ],
            options={
                'verbose_name': 'Tunnistamo Session Element',
                'verbose_name_plural': 'Tunnistamo Session Elements',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='sessionelement',
            index=models.Index(fields=['content_type', 'object_id'], name='users_sessi_content_dffeb4_idx'),
        ),
        migrations.AddConstraint(
            model_name='sessionelement',
            constraint=models.UniqueConstraint(fields=('session_id', 'content_type', 'object_id'), name='unique_session_element'),
        ),
    ]
