# Generated by Django 2.2.24 on 2021-06-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_add_tunnistamo_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='tunnistamosession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ended at'),
        ),
    ]
