# Generated by Django 2.2.24 on 2021-10-20 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_bigger_max_length_for_user_first_and_last_name'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE social_auth_usersocialauth ALTER COLUMN extra_data TYPE JSONB USING extra_data::JSON;",
            reverse_sql="ALTER TABLE social_auth_usersocialauth ALTER COLUMN extra_data TYPE TEXT USING extra_data::TEXT;",
        )
    ]
