# Generated by Django 3.2.8 on 2021-10-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_convert_social_auth_usersocialauth_extra_data_field_to_jsonb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tunnistamosession',
            name='data',
            field=models.JSONField(blank=True, null=True, verbose_name='Session data'),
        ),
        migrations.AlterField(
            model_name='userloginentry',
            name='geo_location',
            field=models.JSONField(blank=True, null=True, verbose_name='geo location'),
        ),
    ]
