# Generated by Django 3.2.8 on 2021-10-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_change_to_generic_jsonfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmethod',
            name='provider_id',
            field=models.CharField(choices=[('eduhelfi', 'eduhelfi'), ('espoo', 'espoo'), ('facebook', 'facebook'), ('github', 'github'), ('google', 'google'), ('helsinki_adfs', 'helsinki_adfs'), ('helsinki_library_asko_adfs', 'helsinki_library_asko_adfs'), ('helsinkiazuread', 'helsinkiazuread'), ('heltunnistussuomifi', 'heltunnistussuomifi'), ('helusername', 'helusername'), ('suomifi', 'suomifi'), ('tunnistamo', 'tunnistamo'), ('yletunnus', 'yletunnus')], max_length=50, unique=True),
        ),
    ]
