# Generated by Django 3.2.8 on 2022-01-21 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


def copy_to_translated(apps, schema_editor):
    LoginMethod = apps.get_model("users", "LoginMethod")
    for login_method in LoginMethod.objects.all():
        login_method.set_current_language(settings.LANGUAGE_CODE)
        login_method.name2 = login_method.name
        login_method.short_description2 = login_method.short_description
        login_method.save()

def copy_from_translated(apps, schema_editor):
    LoginMethod = apps.get_model("users", "LoginMethod")
    for login_method in LoginMethod.objects.all():
        login_method.set_current_language(settings.LANGUAGE_CODE)
        login_method.name = login_method.name2
        login_method.short_description = login_method.short_description2
        login_method.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_loginmethod_provider_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginMethodTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name2', models.CharField(max_length=100)),
                ('short_description2', models.TextField(blank=True, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='users.loginmethod')),
            ],
            options={
                'verbose_name': 'login method Translation',
                'db_table': 'users_loginmethod_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.RunPython(copy_to_translated, copy_from_translated),
        migrations.RemoveField(
            model_name='loginmethod',
            name='name',
        ),
        migrations.RemoveField(
            model_name='loginmethod',
            name='short_description',
        ),
        migrations.RenameField(
            model_name='loginmethodtranslation',
            old_name='name2',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='loginmethodtranslation',
            old_name='short_description2',
            new_name='short_description',
        ),
    ]
