# Generated by Django 3.2.19 on 2023-09-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_add_vakehyvaazuread_to_loginmethod_provider_id_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmethod',
            name='provider_id',
            field=models.CharField(choices=[('eduhelfi', 'eduhelfi'), ('espoo', 'espoo'), ('espooazuread', 'espooazuread'), ('facebook', 'facebook'), ('github', 'github'), ('google', 'google'), ('helsinki_adfs', 'helsinki_adfs'), ('helsinki_library_asko_adfs', 'helsinki_library_asko_adfs'), ('helsinki_tunnus', 'helsinki_tunnus'), ('helsinkiazuread', 'helsinkiazuread'), ('heltunnistussuomifi', 'heltunnistussuomifi'), ('helusername', 'helusername'), ('suomifi', 'suomifi'), ('tunnistamo', 'tunnistamo'), ('vakehyvaazuread', 'vakehyvaazuread'), ('vantaaazuread', 'vantaaazuread'), ('yletunnus', 'yletunnus')], max_length=50, unique=True),
        ),
    ]
