# Generated by Django 2.0.10 on 2019-01-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedRsaKey',
            fields=[
                ('key_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('created', models.DateField()),
                ('expired', models.DateField(null=True)),
            ],
        ),
    ]
