# Generated by Django 2.0.10 on 2019-01-23 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oidc_provider', '0025_user_field_codetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedRSAKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('expired_at', models.DateTimeField(null=True)),
                ('rsakey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oidc_provider.RSAKey')),
            ],
        ),
    ]
