# Generated by Django 2.0.10 on 2019-01-17 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADFSAttributeMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_name', models.CharField(max_length=100)),
                ('out_name', models.CharField(choices=[('primary_sid', 'Primary SID'), ('department_name', 'Department name'), ('email', 'Email'), ('username', 'Username'), ('ad_groups', 'AD Groups'), ('first_name', 'First name'), ('last_name', 'Last name')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ADFSRealm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('adfs_url', models.URLField()),
                ('certificate', models.TextField(editable=False)),
                ('app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.SocialApp')),
            ],
        ),
        migrations.AddField(
            model_name='adfsattributemapping',
            name='realm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_mappings', to='adfs_provider.ADFSRealm'),
        ),
        migrations.AlterUniqueTogether(
            name='adfsattributemapping',
            unique_together={('realm', 'in_name'), ('realm', 'out_name')},
        ),
    ]
