# File: tunnistamo/azure-pipelines.yml

# Continuous integration (CI) triggers cause a pipeline to run whenever you push 
# an update to the specified branches or you push specified tags.
trigger:
  branches:
    include:
    - develop
  paths:
    exclude:
    - README.md

# By default, use self-hosted agents
pool: Default

# Opting out of pull request validation
pr: none

resources:
  repositories:
  # Azure DevOps repository
  - repository: tunnistamo-pipelines
    type: git
    # project/repository
    name: helsinki-profile-tunnistamo/tunnistamo-pipelines

extends:
  template: azure-pipelines.yml@tunnistamo-pipelines
