# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 12:01
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('public_key', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='public key')),
                ('secret_key', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='secret key')),
                ('app_version', models.CharField(max_length=50, verbose_name='app version')),
                ('os', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=20, verbose_name='OS')),
                ('os_version', models.CharField(max_length=50, verbose_name='OS version')),
                ('device_model', models.CharField(blank=True, max_length=50, verbose_name='device model')),
                ('last_used_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='last used at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user device',
                'verbose_name_plural': 'user devices',
            },
        ),
    ]
