# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_add_auth_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('secret_key', models.CharField(max_length=50, verbose_name='secret key')),
                ('scopes', models.CharField(max_length=200, verbose_name='allowed OAuth scopes')),
            ],
        ),
    ]
