# Generated by Django 2.1.8 on 2019-06-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_add_interface_device_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfacedevice',
            name='secret_key',
            field=models.CharField(max_length=128, verbose_name='secret key'),
        ),
    ]
