# Generated by Django 2.0.13 on 2019-04-02 13:13

from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuomiFiAccessLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shorthand', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SuomiFiAccessLevelTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='auth_backends.SuomiFiAccessLevel')),
            ],
            options={
                'verbose_name': 'suomi fi access level Translation',
                'db_table': 'auth_backends_suomifiaccesslevel_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SuomiFiUserAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendly_name', models.CharField(max_length=100, unique=True)),
                ('uri', models.CharField(max_length=100, unique=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='suomifiaccesslevel',
            name='attributes',
            field=models.ManyToManyField(to='auth_backends.SuomiFiUserAttribute'),
        ),
        migrations.AlterUniqueTogether(
            name='suomifiaccessleveltranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
