# Generated by Django 2.2.17 on 2020-11-06 08:42

from django.db import migrations
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth_backends', '0001_suomifi_access_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suomifiaccessleveltranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='auth_backends.SuomiFiAccessLevel'),
        ),
    ]
