# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamlSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_entity_id', models.CharField(max_length=255, verbose_name='Entity Id')),
                ('sp_certificate', models.TextField(verbose_name='SP x509 certificate')),
                ('sp_private_key', models.TextField(verbose_name='SP Private Key')),
                ('idp_entity_id', models.CharField(max_length=255, verbose_name='IDP Entity Id')),
                ('idp_certificate', models.TextField(verbose_name='IDP x509 certificate')),
                ('idp_sso_url', models.URLField(max_length=255, verbose_name='IDP singleSignOnService URL')),
                ('idp_sls_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='IDP singleLogoutService URL')),
                ('technical_contact_name', models.CharField(max_length=255, verbose_name='Technical contact name')),
                ('technical_contact_email', models.EmailField(max_length=255, verbose_name='Technical contact email')),
                ('support_contact_name', models.CharField(max_length=255, verbose_name='Support contact name')),
                ('support_contact_email', models.EmailField(max_length=255, verbose_name='Support contact email')),
                ('organization_name', models.CharField(max_length=255, verbose_name='Organization name')),
                ('organization_display_name', models.CharField(max_length=255, verbose_name='Organization display name')),
                ('organization_url', models.URLField(max_length=255, verbose_name='Organization URL')),
                ('app', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='socialaccount.SocialApp')),
            ],
            options={
                'verbose_name': 'SAML Settings',
                'verbose_name_plural': 'SAML Settings',
            },
        ),
    ]
