# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suomifi_provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamlSettingsTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('service_name', models.CharField(max_length=255, verbose_name='Service name')),
                ('organization_name', models.CharField(max_length=255, verbose_name='Organization name')),
                ('organization_display_name', models.CharField(max_length=255, verbose_name='Organization display name')),
                ('ui_display_name', models.CharField(max_length=255, verbose_name='Suomi.fi UI display name')),
                ('ui_description', models.CharField(max_length=255, verbose_name='Suomi.fi UI description')),
                ('ui_privacy_statement_url', models.URLField(max_length=255, verbose_name='Suomi.fi UI privacy statement URL')),
            ],
            options={
                'verbose_name': 'SAML Settings Translation',
                'db_table': 'suomifi_provider_samlsettings_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='samlsettings',
            name='organization_display_name',
        ),
        migrations.RemoveField(
            model_name='samlsettings',
            name='organization_name',
        ),
        migrations.AddField(
            model_name='samlsettings',
            name='ui_logo_url',
            field=models.URLField(default='', max_length=255, verbose_name='Suomi.fi UI logo URL'),
        ),
        migrations.AddField(
            model_name='samlsettingstranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='suomifi_provider.SamlSettings'),
        ),
        migrations.AlterUniqueTogether(
            name='samlsettingstranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
