# Generated by Django 2.0.9 on 2018-10-15 08:08

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='required_scopes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('email', 'E-mail'), ('profile', 'Profile'), ('address', 'Address'), ('github_username', 'GitHub username'), ('ad_groups', 'AD Groups')], help_text='Select the scopes that this API needs information from. Information from the selected scopes will be included to the API Tokens.', max_length=1000, verbose_name='required scopes'),
        ),
    ]
