# Generated by Django 4.2.14 on 2024-07-31 11:37

from django.db import migrations
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ("oidc_apis", "0003_api_backchannel_logout_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiscopetranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="oidc_apis.apiscope",
                verbose_name="API scope",
            ),
        ),
    ]
